name: where_hearts_meet
description: A Project through which two hearts will feel more connected ..we hope so

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  confetti: ^0.7.0
  shared_preferences: ^2.2.1
  get_it: ^7.6.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_auth: 
  dio: ^5.3.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4
  story_view: ^0.16.3
  get_storage: ^2.1.1
  unicons:
  easy_stepper: ^0.8.3
  photo_view: ^0.15.0
  aws_s3_upload: ^1.5.0
  dots_indicator:
  flutter_animate: ^4.5.0
  flutter_card_swiper: ^7.0.1
  motion_tab_bar: ^2.0.4
  flutter_timer_countdown:
  otp_text_field: ^1.1.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_sign_in: ^6.2.1
  youtube_player_flutter: ^9.0.1
  clay_containers: ^0.3.4
  dotted_border: ^2.1.0
  simple_s3: ^0.3.2


  google_fonts:
  blur:
  lottie:
  video_player: ^2.2.19
  flutter_svg: ^1.0.0
  url_launcher: ^6.1.7
  carousel_slider: ^4.2.1
  chewie:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/images/
     - asset/icons/
     - asset/icons/lottie/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-Light.ttf
          weight: 400
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-Regular.ttf
          weight: 500
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-Medium.ttf
          weight: 600
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-SemiBold.ttf
          weight: 700
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-Bold.ttf
          weight: 800
        - asset: asset/fonts/plusjakarta/PlusJakartaSans-ExtraBold.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
